### ISSUE TITLE
R handout.pdf typo

### ISSUE THREAD

**Issue by SameOldSamOld** [SangerCytometry/R_flowcytometry_course#1]
... "Transfer the data for plotting." ...

"chnls <- colnames(fcsfile_comp, [7:24])"

Unexpected comma caught out a learner and took a while to fix.

"chnls <- colnames(fcsfile_comp[7:24])"

Worked fine.

**Comment by SangerCytometry** [comment]
Thank you SameOldSamOld
,
The code in the R handout.R file was correct, but that is a typo in the PDF.  Well spotted.

However, your fix is not correct, it should be:
```R
chnls <- colnames(fcsfile_comp[,7:24])
```
The comma denotes that it should look at the x axis for the labels, without the comma it basically takes the rows (cells) 7:24 and copies their column names.  Try both and see the different results.
```R
chnls <- colnames(fcsfile_comp[,7:24])
chnls
chnls <- colnames(fcsfile_comp[7:24])
chnls

#See the different number of cells
fcsfile_comp[,7:24]
fcsfile_comp[7:24]
```
You don't want to transform the linear columns, i.e. FSC and SSC.  This comma thing catches me out all the time!

Thanks again for spotting this.
Chris
